services:
  localstack:
    image: localstack/localstack
    volumes:
      - './localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh'
    ports:
      - 4566:4566
    networks:
      - tinify

  tinify-mock-api:
    image: tinify-mock-api
    build:
      context: ..
      dockerfile: ./config/Dockerfile-mock-webservice
    ports:
      - '8100:80'
    volumes:
      - ../test/mock-tinypng-webservice:/var/www/html
    networks:
      - tinify

networks:
  tinify:
    external: true